### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by ccoVeille** [kevincobain2000/gol#25]
- you should add a dependabot/renovatebot to your GitHub actions
- golangci-lint should be part of the test to ensure the context quality of code.

**Comment by ccoVeille** [comment]
I can help you of course

**Comment by kevincobain2000** [comment]
Hi
`dependabot` - yes I should have been adding it. If you can add it quickly that is cool too, will appreciate it. I got little busy today with the #24 

**Step 0)** `golanglint-ci` - oops. I added that from my [previous project](https://github.com/kevincobain2000/gobrew) which had a lot of lint errors, so instead of failing I started counting the progress. Actually there are no errors on this repo - so I should update the following to fail on errors.

ASIS

```
      - name: Lint Errors
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: go-lint-errors
          command: golangci-lint run ./... | grep  -c "\^"
```

TOBE

```sh
      - name: Lint Errors
        run: golangci-lint run ./...
```

https://github.com/kevincobain2000/gol/blob/22fa4a95cf84557767a236691e634b3fc4e9c2c3/.github/workflows/coveritup.yml#L65

**Step 1)** And finally update the README to remove the badges and graphs.
